import type {
  ElementProfile,
  ProfileMatch,
  ProfileTier,
} from "@ib/shared";

export type { ElementProfile, ProfileMatch, ProfileTier };

const ONBOARDING_DATA_ATTRS = [
  "data-onboarding",
  "data-ib",
  "data-testid",
  "data-cy",
  "data-test-id",
];

/** CSS-escape an attribute selector value. */
function cssEscape(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  return value.replace(/(["\\])/g, "\\$1");
}

/**
 * Build a 5-tier element profile, capturing whatever signals are available so
 * a future page-load can re-discover the element via the cascade in
 * findElement().
 */
export function recordProfile(el: Element): ElementProfile {
  const profile: ElementProfile = {
    schema: 1,
    tagName: el.tagName.toLowerCase(),
  };

  // Tier 1: data attribute
  for (const name of ONBOARDING_DATA_ATTRS) {
    const value = el.getAttribute(name);
    if (value !== null && value !== "") {
      profile.dataAttr = { name, value };
      break;
    }
  }

  // Tier 2: id (skip auto-generated ones with a digit-heavy suffix)
  const id = el.id;
  if (id && !looksAutoGenerated(id)) {
    profile.id = id;
  }

  // Tier 3: a11y / semantic
  const role = el.getAttribute("role");
  if (role) profile.role = role;
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) profile.ariaLabel = ariaLabel;

  // Tier 4: text content
  const text = (el.textContent ?? "").trim();
  if (text && text.length <= 80) {
    profile.text = text;
  }

  // Tier 5: structural DOM path (always recorded as a last resort)
  profile.domPath = computeDomPath(el);

  return profile;
}

function looksAutoGenerated(id: string): boolean {
  // CSS-modules / Emotion / styled-components ids tend to be hash-like.
  return /^[a-z]{0,8}[-_]?[a-z0-9]{6,}$/i.test(id) && /\d/.test(id);
}

/**
 * Walk up to <html> building a sibling-indexed selector path. Capped at 8
 * levels to keep things under control.
 */
function computeDomPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;
  let depth = 0;
  while (current && current !== document.documentElement && depth < 8) {
    const tag = current.tagName.toLowerCase();
    const parentEl: Element | null = current.parentElement;
    if (!parentEl) {
      parts.unshift(tag);
      break;
    }
    const tagName = current.tagName;
    const siblings: Element[] = Array.from(parentEl.children).filter(
      (c: Element) => c.tagName === tagName,
    );
    if (siblings.length === 1) {
      parts.unshift(tag);
    } else {
      const idx = siblings.indexOf(current) + 1;
      parts.unshift(`${tag}:nth-of-type(${idx})`);
    }
    current = parentEl;
    depth += 1;
  }
  return parts.join(" > ");
}

/**
 * Resolve an element from a profile, trying each tier in order. Returns the
 * matched element + the tier that succeeded, or null if all tiers fail.
 */
export function findElement(
  profile: ElementProfile,
  scope: ParentNode = document,
): ProfileMatch | null {
  // Tier 1: data attribute
  if (profile.dataAttr) {
    const sel = `[${cssEscape(profile.dataAttr.name)}="${cssEscape(profile.dataAttr.value)}"]`;
    const el = scope.querySelector(sel);
    if (el) return { element: el, tier: 1 };
  }

  // Tier 2: id
  if (profile.id) {
    const el = scope.querySelector(`#${cssEscape(profile.id)}`);
    if (el) return { element: el, tier: 2 };
  }

  // Tier 3: a11y / semantic
  if (profile.role || profile.ariaLabel) {
    const parts: string[] = [profile.tagName];
    if (profile.role) parts.push(`[role="${cssEscape(profile.role)}"]`);
    if (profile.ariaLabel) {
      parts.push(`[aria-label="${cssEscape(profile.ariaLabel)}"]`);
    }
    const sel = parts.join("");
    const el = scope.querySelector(sel);
    if (el) return { element: el, tier: 3 };
    // Fall back: any tag with that aria-label (lots of devs put it on a span).
    if (profile.ariaLabel) {
      const fallback = scope.querySelector(
        `[aria-label="${cssEscape(profile.ariaLabel)}"]`,
      );
      if (fallback) return { element: fallback, tier: 3 };
    }
  }

  // Tier 4: text content
  if (profile.text) {
    const candidates = scope.querySelectorAll<HTMLElement>(profile.tagName);
    for (const c of Array.from(candidates)) {
      if ((c.textContent ?? "").trim() === profile.text) {
        return { element: c, tier: 4 };
      }
    }
  }

  // Tier 5: structural path
  if (profile.domPath) {
    try {
      const el = scope.querySelector(profile.domPath);
      if (el) return { element: el, tier: 5 };
    } catch {
      // Invalid selector; fall through.
    }
  }

  return null;
}
