import type {
  ElementProfile,
  ProfileMatch,
  ProfileTier,
} from "@ib/shared";

export type { ElementProfile, ProfileMatch, ProfileTier };

const ONBOARDING_DATA_ATTRS = [
  "data-onboarding",
  "data-ib",
  "data-testid",
  "data-cy",
  "data-test-id",
];

/**
 * Class-similarity matching threshold (tier 5). An element is accepted if at
 * least this fraction of the *recorded* stable classes are still present on
 * the candidate. Recall, not Jaccard — we don't penalise newly-added classes.
 */
export const CLASS_SIMILARITY_THRESHOLD = 0.95;

/** Don't bother running the class tier on near-classless elements. */
const MIN_CLASSES_FOR_TIER_5 = 2;

/** CSS-escape an attribute selector value. */
function cssEscape(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  return value.replace(/(["\\])/g, "\\$1");
}

/**
 * Strip classes that look build-generated (CSS-modules suffixes, emotion /
 * styled-components hashes). We keep Tailwind utilities, BEM, and plain
 * semantic class names, which are the signals that actually persist across
 * builds.
 */
export function filterStableClasses(classList: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of classList) {
    const cls = raw.trim();
    if (!cls || seen.has(cls)) continue;
    if (looksGeneratedClass(cls)) continue;
    seen.add(cls);
    out.push(cls);
  }
  return out;
}

function looksGeneratedClass(cls: string): boolean {
  // Emotion: `css-1j3kfly`, `css-abc123def`
  if (/^css-[a-z0-9]{5,}$/i.test(cls)) return true;
  // styled-components: `sc-bdVaJa`, `sc-AxjAm`
  if (/^sc-[a-zA-Z]{6,}$/.test(cls)) return true;
  // CSS-modules: `Button_root__abc123`, `Card__xyz789`
  if (/__[a-zA-Z0-9]{5,}$/.test(cls)) return true;
  // CSS-modules without leading separator: `_3kbF9X`
  if (/^_[a-zA-Z0-9]{5,}$/.test(cls)) return true;
  return false;
}

/**
 * Build a 6-tier element profile, capturing whatever signals are available so
 * a future page-load can re-discover the element via the cascade in
 * findElement().
 */
export function recordProfile(el: Element): ElementProfile {
  const profile: ElementProfile = {
    schema: 1,
    tagName: el.tagName.toLowerCase(),
  };

  // Tier 1: data attribute
  for (const name of ONBOARDING_DATA_ATTRS) {
    const value = el.getAttribute(name);
    if (value !== null && value !== "") {
      profile.dataAttr = { name, value };
      break;
    }
  }

  // Tier 2: id (skip auto-generated ones with a digit-heavy suffix)
  const id = el.id;
  if (id && !looksAutoGenerated(id)) {
    profile.id = id;
  }

  // Tier 3: a11y / semantic
  const role = el.getAttribute("role");
  if (role) profile.role = role;
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) profile.ariaLabel = ariaLabel;

  // Tier 4: text content
  const text = (el.textContent ?? "").trim();
  if (text && text.length <= 80) {
    profile.text = text;
  }

  // Tier 5: stable class list (Tailwind / BEM / semantic names)
  const classes = filterStableClasses(Array.from(el.classList));
  if (classes.length >= MIN_CLASSES_FOR_TIER_5) {
    profile.classes = classes;
  }

  // Tier 6: structural DOM path (always recorded as a last resort)
  profile.domPath = computeDomPath(el);

  return profile;
}

function looksAutoGenerated(id: string): boolean {
  // CSS-modules / Emotion / styled-components ids tend to be hash-like.
  return /^[a-z]{0,8}[-_]?[a-z0-9]{6,}$/i.test(id) && /\d/.test(id);
}

/**
 * Walk up to <html> building a sibling-indexed selector path. Capped at 8
 * levels to keep things under control.
 */
function computeDomPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;
  let depth = 0;
  while (current && current !== document.documentElement && depth < 8) {
    const tag = current.tagName.toLowerCase();
    const parentEl: Element | null = current.parentElement;
    if (!parentEl) {
      parts.unshift(tag);
      break;
    }
    const tagName = current.tagName;
    const siblings: Element[] = Array.from(parentEl.children).filter(
      (c: Element) => c.tagName === tagName,
    );
    if (siblings.length === 1) {
      parts.unshift(tag);
    } else {
      const idx = siblings.indexOf(current) + 1;
      parts.unshift(`${tag}:nth-of-type(${idx})`);
    }
    current = parentEl;
    depth += 1;
  }
  return parts.join(" > ");
}

/**
 * Resolve an element from a profile, trying each tier in order. Returns the
 * matched element + the tier that succeeded, or null if all tiers fail.
 */
export function findElement(
  profile: ElementProfile,
  scope: ParentNode = document,
): ProfileMatch | null {
  // Tier 1: data attribute
  if (profile.dataAttr) {
    const sel = `[${cssEscape(profile.dataAttr.name)}="${cssEscape(profile.dataAttr.value)}"]`;
    const el = scope.querySelector(sel);
    if (el) return { element: el, tier: 1 };
  }

  // Tier 2: id
  if (profile.id) {
    const el = scope.querySelector(`#${cssEscape(profile.id)}`);
    if (el) return { element: el, tier: 2 };
  }

  // Tier 3: a11y / semantic
  if (profile.role || profile.ariaLabel) {
    const parts: string[] = [profile.tagName];
    if (profile.role) parts.push(`[role="${cssEscape(profile.role)}"]`);
    if (profile.ariaLabel) {
      parts.push(`[aria-label="${cssEscape(profile.ariaLabel)}"]`);
    }
    const sel = parts.join("");
    const el = scope.querySelector(sel);
    if (el) return { element: el, tier: 3 };
    // Fall back: any tag with that aria-label (lots of devs put it on a span).
    if (profile.ariaLabel) {
      const fallback = scope.querySelector(
        `[aria-label="${cssEscape(profile.ariaLabel)}"]`,
      );
      if (fallback) return { element: fallback, tier: 3 };
    }
  }

  // Tier 4: text content
  if (profile.text) {
    const candidates = scope.querySelectorAll<HTMLElement>(profile.tagName);
    for (const c of Array.from(candidates)) {
      if ((c.textContent ?? "").trim() === profile.text) {
        return { element: c, tier: 4 };
      }
    }
  }

  // Tier 5: class similarity (Tailwind / BEM / semantic class set)
  if (profile.classes && profile.classes.length >= MIN_CLASSES_FOR_TIER_5) {
    const match = findByClassSimilarity(
      profile.tagName,
      profile.classes,
      scope,
    );
    if (match) return { element: match, tier: 5 };
  }

  // Tier 6: structural path
  if (profile.domPath) {
    try {
      const el = scope.querySelector(profile.domPath);
      if (el) return { element: el, tier: 6 };
    } catch {
      // Invalid selector; fall through.
    }
  }

  return null;
}

/**
 * Find the best-matching element by class-set recall: of the classes we
 * recorded, what fraction does each candidate still carry? Highest wins,
 * ties broken by document order. Returns null if nothing meets the threshold.
 */
function findByClassSimilarity(
  tagName: string,
  recorded: readonly string[],
  scope: ParentNode,
): Element | null {
  const recordedSet = new Set(recorded);
  const recordedCount = recordedSet.size;
  if (recordedCount === 0) return null;

  let bestEl: Element | null = null;
  let bestScore = 0;

  const candidates = scope.querySelectorAll(tagName);
  for (const el of Array.from(candidates)) {
    const candidateClasses = filterStableClasses(Array.from(el.classList));
    if (candidateClasses.length === 0) continue;

    let matched = 0;
    for (const c of candidateClasses) {
      if (recordedSet.has(c)) matched += 1;
    }
    const score = matched / recordedCount;
    if (score > bestScore) {
      bestScore = score;
      bestEl = el;
    }
  }

  return bestScore >= CLASS_SIMILARITY_THRESHOLD ? bestEl : null;
}
